###
# only for SaaS
# @name login
POST https://login.cloud.camunda.io/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{CAMUNDA_CLIENT_ID}}
&client_secret={{CAMUNDA_CLIENT_SECRET}}
&audience=zeebe.camunda.io
&scope=Zeebe,Operate,Tasklist,Secrets

###
# add stuff from .env
.env

###
# deploy LOCAL BPMN
POST {{ZEEBE_REST_ADDRESS}}/v2/deployments
# Authorization: Bearer {{login.access_token}}
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="resources"; filename="safeguard-agent.bpmn"
Content-Type: application/xml

< ./../safeguard-agent.bpmn
------Boundary--


### Start LLM Safeguard
# @name userPromptSafeguarded

@userPromptFile = safeguard-unsafeprompt.txt
@systemPromptFile = safeguard-systemprompt.txt

{{
  const fs = require('fs');
  const path = require('path');

  let userPrompt = fs.readFileSync(path.join(__dirname, `./prompts/${userPromptFile}`), 'utf8');
  userPrompt = userPrompt.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/"/g, '\\"');
  exports.userPrompt = userPrompt;

  let systemPrompt = fs.readFileSync(path.join(__dirname, `./prompts/${systemPromptFile}`), 'utf8');
  systemPrompt = systemPrompt.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/"/g, '\\"');

  exports.systemPrompt = systemPrompt;
  // console.info(exports)
}}

POST {{ZEEBE_REST_ADDRESS}}/v2/process-instances
# Authorization: Bearer {{login.access_token}}
Content-Type: application/json

{
  "processDefinitionId": "safeguard-agent",
  "variables": {
    "systemPrompt": "{{systemPrompt}}",
    "userPromptToSafeguard": "{{userPrompt}}"
  },
  "awaitCompletion": true
}

{{
  // const responseXML = userPromptSafeguarded.variables.responseXML;
  // const formatted = require('xml-formatter')(responseXML, {
  //   indentation: '  ',
  //   collapseContent: true
  // });
  console.info("agent result: \n", userPromptSafeguarded.variables.responseJSONString);
  
  console.info("execution time (sec):", userPromptSafeguarded.variables.execTime);
  
  console.info("token usage:", userPromptSafeguarded.variables.tokenUsage);
}}