x-spring-app: &spring-app
  image: maven:3.9-eclipse-temurin-25 # includes Maven + JDK 25
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    # expects a local c8run as go-to Camunda instance
    CAMUNDA_CLIENT_GRPC_ADDRESS: ${CAMUNDA_GRPC_ADDRESS:-http://host.docker.internal:26500}
    CAMUNDA_CLIENT_REST_ADDRESS: ${CAMUNDA_BASE_URL:-http://host.docker.internal:8080}
    SPRING_DEVTOOLS_RESTART_ENABLED: "true"
    # SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
    MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"

    
# for Spring HotReload https://docs.spring.io/spring-boot/reference/using/devtools.html
## Add DevTools to Each Spring Boot App
## In each app's pom.xml:
# <dependencies>
#     <!-- ... other dependencies ... -->
#
#     <dependency>
#         <groupId>org.springframework.boot</groupId>
#         <artifactId>spring-boot-devtools</artifactId>
#         <scope>runtime</scope>
#         <optional>true</optional>
#     </dependency>
# </dependencies>


services:
  ai-firewall-agent:
    <<: *spring-app
    working_dir: /app
    volumes:
      - .:/app
      - maven-cache:/root/.m2
    command: mvn spring-boot:run 
    ports:
      - "${AI_FIREWALL_AGENT_PORT:-8081}:8080"

volumes:
  maven-cache: